# Generated by Django 5.0.3 on 2024-05-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('userid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('appraiseename', models.CharField(max_length=256)),
                ('department', models.CharField(max_length=128)),
                ('designation', models.CharField(max_length=128)),
                ('performancerating', models.IntegerField(max_length=5)),
                ('comments', models.TextField(max_length=2000)),
            ],
        ),
    ]
