# Generated by Django 5.0.3 on 2024-05-09 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appraisal',
            old_name='appraiseename',
            new_name='name',
        ),
    ]
