# Generated by Django 5.0.3 on 2024-05-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_rename_appraiseename_appraisal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisal',
            name='userid',
        ),
        migrations.AddField(
            model_name='appraisal',
            name='appraiseeuserid',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='appraiseruserid',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
