# Generated by Django 5.0.3 on 2024-05-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0003_remove_appraisal_userid_appraisal_appraiseeuserid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grievance', models.TextField()),
            ],
        ),
    ]
