# Generated by Django 5.0.3 on 2024-05-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0004_grievance'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='department',
            field=models.CharField(default='admin', max_length=128),
        ),
        migrations.AddField(
            model_name='grievance',
            name='designation',
            field=models.CharField(default='clerk', max_length=128),
        ),
        migrations.AddField(
            model_name='grievance',
            name='name',
            field=models.CharField(default='xyz', max_length=256),
        ),
        migrations.AddField(
            model_name='grievance',
            name='userid',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
