# Generated by Django 5.0.3 on 2024-05-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0005_grievance_department_grievance_designation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grievance',
            old_name='userid',
            new_name='appraiseeuserid',
        ),
        migrations.AddField(
            model_name='grievance',
            name='appraiseruserid',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
