# Generated by Django 5.0.3 on 2024-05-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('userid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.IntegerField(max_length=10)),
                ('createdby', models.CharField(max_length=50)),
                ('createdfor', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=500)),
            ],
        ),
    ]
