# Generated by Django 5.0.3 on 2024-05-07 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisal',
            name='createdby',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='createdfor',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='reason',
        ),
        migrations.AddField(
            model_name='appraisal',
            name='appraiseename',
            field=models.CharField(default=12345, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appraisal',
            name='appraisername',
            field=models.CharField(default=12345, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appraisal',
            name='comments',
            field=models.TextField(default=12345, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appraisal',
            name='department',
            field=models.CharField(default=12345, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appraisal',
            name='designation',
            field=models.CharField(default=12345, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appraisal',
            name='performancerating',
            field=models.IntegerField(default=12345, max_length=5),
            preserve_default=False,
        ),
    ]
