# Generated by Django 5.0.3 on 2024-05-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_remove_appraisal_createdby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('userid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('department', models.CharField(max_length=128)),
                ('designation', models.CharField(max_length=128)),
                ('grievances', models.TextField(max_length=2000)),
            ],
        ),
    ]
