# Generated by Django 5.0.3 on 2024-05-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_grievance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appraisal',
        ),
        migrations.DeleteModel(
            name='Grievance',
        ),
    ]
