# Generated by Django 5.0.3 on 2024-04-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('dob', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('department', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('contactno', models.CharField(max_length=10)),
                ('emailaddress', models.CharField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
    ]
