# Generated by Django 5.0.3 on 2024-04-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisalapp', '0002_admin_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='email',
        ),
        migrations.RemoveField(
            model_name='login',
            name='status',
        ),
        migrations.AddField(
            model_name='admin',
            name='userid',
            field=models.CharField(default=1, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='userid',
            field=models.CharField(default='aks007', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='login',
            name='userid',
            field=models.CharField(default='aks007', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='admin',
            name='emailaddress',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emailaddress',
            field=models.EmailField(max_length=254),
        ),
    ]
