# Generated by Django 5.0.3 on 2024-04-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisalapp', '0003_remove_login_email_remove_login_status_admin_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='userid',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
