# Generated by Django 5.0.3 on 2024-04-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisalapp', '0004_alter_employee_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='password',
            field=models.CharField(default=123, max_length=30),
            preserve_default=False,
        ),
    ]
