# Generated by Django 5.0.3 on 2024-05-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisalapp', '0005_admin_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default=12345, max_length=30),
            preserve_default=False,
        ),
    ]
